[package]
name = "libbf"
version = "0.0.1"
authors = ["yoh2 <yoh2.sdj@gmail.com>"]
edition = "2021"
description = "Brainfu*k and derived language interpreter library"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0"